name: ClickTpa
version: 1.7.5
main: com.jklmao.plugin.ClickTpa
authors: [ jklmao ]
description: Simple TPA plugin for Spigot/Paper Software
loadbefore: [EssentialsX]
commands:
  tpa:
    usage: /<command>
    aliases: [tpa, teleport]
  tpahere:
    usage: /<command>
    aliases: [tpahere]
  tpaccept:
    usage: /<command>
    aliases: [tpaccept, tpyes]
  tpadeny:
    usage: /<command>
    aliases: [tpdeny, tpno]
  tpo:
    usage: /<command>
    alises: [tpo, tp]
  tpohere:
    usage: /<command>
    aliases: [tpohere, s, tphere]
  tptoggle:
    usage: /<command>
  tpacancel:
    usage: /<command>
    aliases: [tpcancel]
  clicktparl:
    usage: /<command>
    aliases: [ctparl]
